# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d68bf0aa3df4a0499df6e3350af65916"
name = "Shipduniya"
application_url = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testmyapp11.myshopify.com"

[webhooks]
api_version = "2026-01"

  # App uninstall
  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/webhooks/app_uninstalled"

  # Orders
  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/webhooks/orders_create"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/webhooks/orders_updated"

  # --- GDPR / Compliance (MANDATORY) ---
  [[webhooks.subscriptions]]
  uri = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/webhooks/customers_data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/webhooks/customers_redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/webhooks/shop_redact"
  compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_analytics,read_fulfillment_constraint_rules,read_fulfillments,read_inventory_shipments,read_inventory_shipments_received_items,read_orders,read_shipping,write_fulfillment_constraint_rules,write_fulfillments,write_inventory_shipments,write_inventory_shipments_received_items,write_orders,write_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://doorships-service-267214421211.asia-south1.run.app/api/shopify/auth/callback"
]
